### ISSUE TITLE
when a power cut issue happens when transaction running , in steve still its showing in charging and active transaction

### ISSUE THREAD

**Issue by nb4787** [matth-x/MicroOcpp#100]
how to resolve power cut happens , device should show un-available , it should disappear from active transaction .
can you explain how to resolve it?

**Comment by nb4787** [comment]
@matth-x PLEASE RESPOND for this issue

**Comment by matth-x** [comment]
Sorry that your issue remained unanswered. I'm closing this assuming it's no longer relevant.
