### ISSUE TITLE
How can I add idTag on endTransaction?

### ISSUE THREAD

**Issue by TDVSVI** [matth-x/MicroOcpp#148]
Hello, everyone.
I would like to add idTag on endTransaction.

What should I do?

**Comment by ISCAETY** [comment]
You can add  add idTag on endTransaction by add this code to ConnectorStatus.cpp 
in void ConnectorStatus::endTransaction(const char *reason) 


`const char *idTag = transaction->getIdTag();
if (idTag)
{
            transaction->setStopIdTag(idTag);
}`

**Comment by matth-x** [comment]
Update: starting from version 0.3.0, the stop IdTag can be set via `endTransaction`:

https://github.com/matth-x/MicroOcpp/blob/1eff6e5dd9cc7b8676febe740136c8a7ecfdbe09/src/MicroOcpp.h#L152
