### ISSUE TITLE
ESP8266 Does not connect to Steve Linux

### ISSUE THREAD

**Issue by philbrickWireless** [matth-x/MicroOcpp#155]
Hi @matth-x ,

I setup SteVe on Linux 20.4 and it is running.
But I am able to connect ESP8266 sample code to my SteVe server.

Changes I made:
On Linux Steve side-
1) cd /etc/mysql/mariadb.conf.d/50-server.cnf  --> Changed the binding address to my IP address 
2) main.properties: IP address changed to mine.
3) Database kept it default as yours steve default given.
4) Bridged Adapter Mode for network is selected 
5)   UFW Firewall configuration also done.
6) Charge point added going from Steve->DataManagement-> And add new one which is used in esp8266 URL 

On ESP8266
Host: "192.168.0.112"
Port: 8080
URL: "ws://192.168.0.112:8080/steve/websocket/CentralSystemService/esp82"
Tried directly giving the websocket Host,URL and Port.

Still it keeps on showing Disconnected

**Comment by matth-x** [comment]
Sorry that your issue remained unanswered. I'm closing this assuming it's no longer relevant.
