### ISSUE TITLE
Query regarding reservation

### ISSUE THREAD

**Issue by RamanpreetKaur1998** [matth-x/MicroOcpp#163]
Here are some doubts regarding reservation:
1. No reservation ID is being sent in Start Transaction, even if the connector was reserved. As per OCPP1.6
"If a transaction for the reserved idTag is started, then Charge Point SHALL send the reservationId in
the StartTransaction.req PDU (see Start Transaction) to notify the Central System that the reservation is
terminated." 
2. RemoteStartTransaction.req is being accepted even if the connector is reserved with other IdTag. As per OCPP1.6
"If the Charge Point accepts the reservation request, then it SHALL refuse charging for all incoming
idTags on the reserved connector, except when the incoming idTag or the parent idTag match the idTag
or parent idTag of the reservation."

How do I proceed further?
Do let me know if you plan to work on these issues or am I missing something?

**Comment by shardul10** [comment]
May I please know how was this resolved? I am still seeing #2 with the latest version.
