### ISSUE TITLE
Issue regarding Local Authorization List

### ISSUE THREAD

**Issue by RamanpreetKaur1998** [matth-x/MicroOcpp#179]
Hi @matth-x,

We've been working on Local Authorization List. 

While working on this, we tested this scenerio where SendLocalList.data message is received from server and list of Identifiers are stored at ESP32 end with authentication status and other information. Now if internet connection breaks and we need to start the transaction(charging session) we authenticate the presented IDTag from the list which is present locally, this scenerio works perfectly fine.

But what if we have list of Identifiers present locally and then ESP32 reset is executed. As ESP32 resets itself, initially internet connection is not established and now we need to authorize an IDTag by checking the Identifiers in Local List.

**Doubt :** 
**Is it possible in current version of ArduinoOCPP to access local list and start a transaction when ESP32 is just Powered up and there is NO internet connection present at that moment?**

Let me know if any information is required at my end.
Hope to hear from you soon!

**Comment by matth-x** [comment]
Hi @RamanpreetKaur1998,

This behavior can be activated by changing the configuration `AO_PreBootTransactions` to true.

Please reopen this if you have follow-up questions.
