### ISSUE TITLE
Send MeterValues

### ISSUE THREAD

**Issue by NuriaParra8997** [matth-x/MicroOcpp#199]
Hello,

I'm trying to send meter values using **ocpp_addMeterValueInput** in C, but I don't know how to use this function. 
Does anyone know how to use this function?

**Comment by matth-x** [comment]
The MeterValueInput is a callback function which returns the current meter reading when it is executed. For example:

```cpp
//this register is always 42Wh, but in a real world scenario, the electricity meter would update it
float dummy_energy_register = 42.f;

//defined in your user code, but the library will call it later to fetch the energy register value
float get_energy_callback() {
    return dummy_energy_register;
}

void app_main() {
    //setup code ...

    ocpp_addMeterValueInput(get_energy_callback, "Energy.Active.Import.Register", "Wh", NULL, NULL);

    //...
}
```

When the library is configured with a MeterValueInput, it will automatically send MeterValues messages regularly. To test this, start a transaction and wait for 60 seconds.

Feel free to reopen if you have follow-up questions.

**Comment by ap9389552** [comment]
hi @matth-x 
![Screenshot 2024-10-18 173651](https://github.com/user-attachments/assets/d95edde7-6d50-4b43-b754-9efce82aaa41)
