### ISSUE TITLE
HeartbeatInterval negative

### ISSUE THREAD

**Issue by NuriaParra8997** [matth-x/MicroOcpp#209]
Hello everyone,
I've noticed that if the charging point receives a configuration value HeartbeatInterval = -2 (a negative value), it returns "Accepted" to the backend. 
Shouldn't it reject it? 
How can I modify this?

Thanks!

**Comment by matth-x** [comment]
Hi @NuriaParra8997,

Thanks for sharing your finding! The ChangeConfiguration still lacks range checks in most cases, unfortunately. However, in the develop branch, the library is already prepared for it and you can specify custom validators at your needs:

```cpp
#include <MicroOcpp/Core/Configuration.h>

void setup() {

    // after OCPP lib has been initialized, set custom validator(s)
    MicroOcpp::registerConfigurationValidator("HeartbeatInterval", [] (const char *value) {
        bool isValid;
        //TODO try to parse value as int and check if it is in range
        return isValid;
    }
}

```

In previous versions of MicroOcpp (starting from v0.3.0), setting validators has only been possible for String configurations (the same way like they are set for [MeterValuesSampledData](https://github.com/matth-x/MicroOcpp/blob/38f1e6bd629ccbae35ede7e134b794d7e8a170c3/src/MicroOcpp/Model/Metering/MeteringService.cpp)).
