### ISSUE TITLE
How can i use Send Local List communication? 

### ISSUE THREAD

**Issue by demirschmid61** [matth-x/MicroOcpp#221]
Hi @matth-x ,

I want to use an operation initiated by CS related to the Local Authorization list. I could not find this operation, can you please help me out?

**Comment by matth-x** [comment]
Hi @demirschmid61, the OCPP lib uses the LocalAuthorizationList in the following scenarios:

- when using the `beginTransaction(...)` and `endTransaction(...)` functions for starting and stopping transactions, the OCPP lib queries the LocalAuthList for the given idTag (also depends on the configs LocalAuthListEnabled, LocalAuthorizeOffline and LocalPreAuthorize)
- you can also query the LocalAuthList programmatically over the `AuthorizationService` class. In the following code snippet, the relevant entry of the LocalAuthList is fetched and assigned to the localAuth pointer (`model` can be initialized with `auto& model = getOcppContext()->getModel();`):

https://github.com/matth-x/MicroOcpp/blob/540d20f50f81863b6463019a8f9a3006e55d8537/src/MicroOcpp/Model/ConnectorBase/Connector.cpp#L540-L560
