### ISSUE TITLE
Unable to connect with Steve using postman

### ISSUE THREAD

**Issue by chandan-ultraviolette** [matth-x/MicroOcpp#222]
I am able to start the SteVe but when I am trying to connect using a postman, I am facing an issue, unable to connect. Sharing the screenshot of my change, any suggestions? I tried connecting with both 192.168 and 10.0 ws url.

![image](https://github.com/matth-x/MicroOcpp/assets/126255050/5e074b93-165a-46df-abc4-70f7f59c083a)

![image](https://github.com/matth-x/MicroOcpp/assets/126255050/38265224-aaca-400e-a9d4-3caadcb78dfe)

![image](https://github.com/matth-x/MicroOcpp/assets/126255050/c3603f99-cac2-46fa-be41-65121140fe86)

Logs are 'No protocol (OCPP version) is specified".

![image](https://github.com/matth-x/MicroOcpp/assets/126255050/7c07f212-4e38-428e-a457-d454d540bfc5)

**Comment by FlxMojojojo** [comment]
@chandan-ultraviolette Post your curl request here ? Let me check.

**Comment by chandan-ultraviolette** [comment]
@FlxMojojojo Request: ws://192.168.128.230:8080/steve/websocket/CentralSystemService/uv_box_001

**Comment by FlxMojojojo** [comment]
@chandan-ultraviolette Please also share the headers that require handshake ?

**Comment by chandan-ultraviolette** [comment]
@chandan-ultraviolette  I am not aware what should we send  in header, may be that's the issue.

**Comment by FlxMojojojo** [comment]
A WebSocket connection with steve is is an http request first that is sent with headers to upgrade the connection to WebSocket.  Headers play a key role here. Also, While connecting to steve WebSocket service you need to understand the connection request sent by the OCPP charger.

**Comment by chandan-ultraviolette** [comment]
Okay, I have not much idea on this, can you help ?

![image](https://github.com/matth-x/MicroOcpp/assets/126255050/9887b806-0254-4c9f-b5cd-c555c9ce993f)

**Comment by matth-x** [comment]
WebSockets have a protocol attribute. Most generic WebSocket clients contain a free-text input field for the protocol specifier. The value must be "ocpp1.6" then.

**Comment by FlxMojojojo** [comment]
@chandan-ultraviolette For you reference - Ps. You are in indiranagar we are in HSR ;) 
 
![image](https://github.com/matth-x/MicroOcpp/assets/122096144/3ebb4175-304a-458c-975e-d2e7785aaa18)

**Comment by chandan-ultraviolette** [comment]
Btw I am hosting Steve on PC, which setting do I need to change to connect it from any network. Currently unable to connect from other network
