### ISSUE TITLE
a small flaw will cause a exception

### ISSUE THREAD

**Issue by zhushengsheng001** [matth-x/MicroOcpp#224]
Hi matth-x,
    The lines in Platform.cpp, will lead to a exception if the paramter console_out is a nullptr.
    void mocpp_set_console_out(void (*console_out)(const char *msg)) {
        MicroOcpp::mocpp_console_out_impl = console_out;
        console_out("[OCPP] console initialized\n");
   }

**Comment by matth-x** [comment]
Hi @zhushengsheng001,

Thanks a ton! Of course it should be possible to reset the custom console.
