### ISSUE TITLE
Get configuration parameters

### ISSUE THREAD

**Issue by NuriaParra8997** [matth-x/MicroOcpp#248]
Hello everyone,
How can configuration parameters be obtained? For example, HeartbeatInterval or MeterValueSampleInterval?

Thanks!!

**Comment by matth-x** [comment]
Hi @NuriaParra8997,

Use this code snippet to fetch, read and set Configurations:

```cpp
std::shared_ptr<MicroOcpp::Configuration> connectionTimeOutInt = MicroOcpp::declareConfiguration<int>("ConnectionTimeOut", 30);
printf("value: %i", connectionTimeOutInt->getInt()); //get value
connectionTimeOutInt->setInt(40); //set value
```

Also `#include <MicroOcpp/Core/Configuration.h>` to get access to the Configuration API. The configurations are fully loaded after `mocpp_initialize(...)`.

For bool or String Configs, the function signatures need to be adapted accordingly:

https://github.com/matth-x/MicroOcpp/blob/735efa29805d33723d80cd351e4ca773b0d96a3e/src/MicroOcpp/Core/Configuration.cpp#L162-L164

https://github.com/matth-x/MicroOcpp/blob/735efa29805d33723d80cd351e4ca773b0d96a3e/src/MicroOcpp/Core/ConfigurationKeyValue.h#L42-L48
