### ISSUE TITLE
How to add configuration key

### ISSUE THREAD

**Issue by demirschmid61** [matth-x/MicroOcpp#255]
Hello,

I am using one variable (setPoint), I want to give access to CMS users to change that setPoint variable. Need to make the setPoint variable as the configuration key.

Can you please tell me how to make the setPoint variable as the configurationKey?

My expectation is, the CMS user should be able to change that configurationKey (setPoint).

Is it possible?

**Comment by matth-x** [comment]
Hi @demirschmid61,

Yes, it is possible. You can declare custom configs which the library will handle like any other configuration then. Here is the how-to: https://github.com/matth-x/MicroOcpp/issues/248#issuecomment-1883585103

**Comment by demirschmid61** [comment]
@matth-x ,

Thank you very much, I'll just implement it in the same way.
