### ISSUE TITLE
Use of AuthorizeRemoteTxRequests Configuration Key

### ISSUE THREAD

**Issue by demirschmid61** [matth-x/MicroOcpp#294]
Hello, the details of **AuthorizeRemoteTxRequests** key in my charger is mentioned below.

{"key":"AuthorizeRemoteTxRequests","readonly":true,"value":"true"}

I want to know, what will change if the value of the **AuthorizeRemoteTxRequests** is made true.

**Comment by matth-x** [comment]
Hi,

This behavior is not implemented at the moment. Changing the value to true has no effect.

**Comment by demirschmid61** [comment]
@matth-x Thank you.
