### ISSUE TITLE
Offline Behavior: Session Data Persistence

### ISSUE THREAD

**Issue by jonlarra11** [matth-x/MicroOcpp#298]
Hi Matth,
First of all, congratulations on all the work done so far.
I'm implementing and testing a charging point that handles local lists, and I have an issue:
I have included the IdTag 12345678 in the local list.
If I don't have a connection with the backend (offline), it eventually authorizes with the local list and starts charging correctly with 12345678.
Charging stops correctly.
Then, if the equipment is restarted and I still don't have a connection with the backend:
[OCPP] debug (FilesystemUtils.cpp:73): Loaded JSON file: tx-1-0.jsn
[OCPP] debug (TransactionDeserialize.cpp:237): DUMP TX
[OCPP] debug (TransactionDeserialize.cpp:238): Session | idTag 12345678, active: 0, authorized: 1, deauthorized: 0
[OCPP] debug (TransactionDeserialize.cpp:239): Start RPC | req: 1, conf: 0
[OCPP] debug (TransactionDeserialize.cpp:240): Stop RPC | req: 1, conf: 0
And at this point, ocpp_getTransactionIdTag_m returns 12345678.
Therefore, when trying to start a new charge:
[OCPP] warning (Connector.cpp:730): tx process still running. Please call endTransaction(...) before
When are the Session data reset? When the BootNotification has been accepted?
Is there any way to make it work without a connection to the backend?
Thanks in advance!

**Comment by matth-x** [comment]
Hi @jonlarra11,

There has been an unfortunate regression bug with offline transactions which lead to stuck transactions. v1.0.3 is still affected, but the issue has been fixed on main and I will release the fix with v1.1.0 very soon. Do you use v1.0.3?

Btw. if you need to reset the transaction cache for a reason like this, then you can always send a ClearCache command to the charger, followed by a Reset.

**Comment by matth-x** [comment]
Hi @jonlarra11, this could be related to a recent regression bug which should be fixed in version 1.1.0. Can you check if upgrading does the trick?

**Comment by jonlarra11** [comment]
Ok thanks!
