### ISSUE TITLE
cppcheck fail (cppcheck --force src/MicroOcpp)

### ISSUE THREAD

**Issue by mundel** [matth-x/MicroOcpp#308]
src/MicroOcpp/Operations/GetConfiguration.cpp:138:13: error: There is an unknown macro here somewhere. Configuration is required. If MO_DBG_DEBUG is a macro then please configure it. [unknownMacro]
            MO_DBG_DEBUG("Unknown key: %s", key)

**Comment by matth-x** [comment]
Hi @mundel, thank you for the hint! I recently changed the debug macros and there could indeed be an issue with the new macros definition. I would like to reproduce this. How did you use cppcheck to find that error? Btw. I would be very open to adding cppcheck as a GitHub Action.

**Comment by mundel** [comment]
Hi @matth-x ,
As I mentioned in heading.
Use below command to check:-
cppcheck --force src/MicroOcpp

**Comment by matth-x** [comment]
Couldn't reproduce it here. The output for GetConfiguration (on main) is

````
Checking src/MicroOcpp/Operations/GetConfiguration.cpp ...
67/92 files checked 82% done
``

Any idea what I could have missed?

**Comment by mundel** [comment]
Hi @matth-x 
I was cross check and found with your latest patch this issue is not seen.
I was not sync code from last couple of days.

**Comment by mundel** [comment]
issue not seen with latest code.
