### ISSUE TITLE
Ocpp tags (rfid) 

### ISSUE THREAD

**Issue by retrocoder-78** [matth-x/MicroOcpp#32]
Hello! 

This project is looking great. Congrats on the amazing work! Ocpp has great functionality in respect to id tags. This predominantly looks to RFID as a way to locally authenticate the evse. Identification, start a transaction, stop a transaction. SteVe also has a great implementation for such tags and their management. 

It looks as if OpenEVSE doesn't currently support RFID.  It could be an option in the future or added. What's the possibility of supporting tags in your project, specifically for RFID? 

Thank you so much for your time! 🙂

**Comment by Kundanjhakj** [comment]
Hi @matth-x , 
![Screenshot 2024-07-15 190233](https://github.com/user-attachments/assets/0b327eab-a623-4574-9e70-ec202fb02b7f)
![Screenshot 2024-07-15 190246](https://github.com/user-attachments/assets/90299e3f-5344-437d-b577-e4facd158efa)


In my code, I am able to authorize using ocpp_authorize method, but I am encountering an issue with starting and stopping transactions. 
My task is to ensure that whenever I tap the RFID, the charger should start and stop. I am sharing my code and error screenshots.


// This is my first task to read rfid value
void echo_data(void)
{
    uint8_t *data = (uint8_t *)malloc(BUF_SIZE);
    while (1)
    {
        receive_acknowledgment(data);
        if (data[0] == ACK_TO_RECEIVE)
        {
            send_acknowledgment(ACK_TO_SEND);

            int len = uart_read_bytes(ECHO_UART_PORT_NUM, data, BUF_SIZE, 20 / portTICK_PERIOD_MS);
            if (len > 0)
            {
                data[len] = '\0';

                // Lock the mutex before updating rfid_current_value
                xSemaphoreTake(rfid_mutex, portMAX_DELAY);
                strncpy(rfid_current_value, (char *)data, BUF_SIZE - 1);
                rfid_current_value[BUF_SIZE - 1] = '\0'; // Ensure null-termination
                xSemaphoreGive(rfid_mutex);

                uart_write_bytes(ECHO_UART_PORT_NUM, (const char *)data, len);
            }
        }
    }
    free(data);
}

// This is second task for ocpp

static void ocpp_task(void *arg)
{
    struct mg_mgr mgr;
    mg_mgr_init(&mgr);
    mg_log_set(MG_LL_DEBUG);

    struct OCPP_FilesystemOpt fsopt = { .use = true, .mount = true, .formatFsOnFail = true};
    OCPP_Connection *osock = ocpp_makeConnection(&mgr, EXAMPLE_MO_OCPP_BACKEND, EXAMPLE_MO_CHARGEBOXID, EXAMPLE_MO_AUTHORIZATIONKEY, "", fsopt);
    ocpp_initialize(osock, "ESP-IDF charger", "Tirex", fsopt, false);

    ocpp_setEnergyMeterInput(getEnergyReading);

    while (1) {
        mg_mgr_poll(&mgr, 10);
        ocpp_loop();

        // Lock the mutex before reading rfid_current_value
        xSemaphoreTake(rfid_mutex, portMAX_DELAY);
        if ((rfid_current_value[0] != '\0') && (strlen(rfid_current_value) > 5))
        {
            ESP_LOGI(TAG, "RFID: %s", rfid_current_value);
            ocpp_authorize(rfid_current_value, NULL, NULL, NULL, NULL, NULL);
            vTaskDelay(100 / portTICK_PERIOD_MS);
            ocpp_startTransaction(rfid_current_value, NULL, NULL, NULL, NULL);

            vTaskDelay(100 / portTICK_PERIOD_MS);
            ocpp_endTransaction(rfid_current_value, "EVDisconnected");
            rfid_current_value[0] = '\0'; // Clear the RFID value after use
        }
        xSemaphoreGive(rfid_mutex);
        vTaskDelay(100 / portTICK_PERIOD_MS); // Yield to prevent watchdog resets
    }

    ocpp_deinitialize();
    ocpp_deinitConnection(osock);
    mg_mgr_free(&mgr);
}

void app_main(void)
{
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    ESP_LOGI(TAG, "ESP_WIFI_MODE_STA");
    wifi_init_sta();
    init_UART();

    // Initialize the mutex
    rfid_mutex = xSemaphoreCreateMutex();
    if (rfid_mutex == NULL) {
        ESP_LOGE(TAG, "Failed to create RFID mutex");
        return;
    }
    xTaskCreate(echo_task, "uart_echo_task", ECHO_TASK_STACK_SIZE, NULL, 11, NULL);
    xTaskCreate(ocpp_task, "ocpp_task", ECHO_TASK_STACK_SIZE, NULL, 10, NULL); // Increased stack size
}

**Comment by Kundanjhakj** [comment]
Issue solved, There was issue in CMS side, another CMS is now accepting this format.
