### ISSUE TITLE
Stuck between Connected and Disconnected loop

### ISSUE THREAD

**Issue by smd632** [matth-x/MicroOcpp#368]
Here are my Terminal entries:
[main] Wait for WiFi: . connected!

" I can see that the charger has come online but after a few seconds it goes offline. The connector is not available"
On terminal window I see this"
[MO] info (Connection.cpp:72): Disconnected
" I don't get any Heartbeat on the OCPP server. It used to work earlier. This has started happening after I moved the charger to another network."
" Can someone help me please"

**Comment by ap9389552** [comment]
try erase flash whenever you change anything also do check your server is working or not
