### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by dpragosa** [matth-x/MicroOcpp#77]
Using the basic example, shows this error. Any tips?

<img width="914" alt="Screenshot 2022-08-05 at 10 41 34" src="https://user-images.githubusercontent.com/65189372/183050878-dcc91a0d-d583-4732-9e8e-72f002759610.png">

**Comment by matth-x** [comment]
Sorry that your issue remained unanswered. I'm closing this assuming it's no longer relevant.
