### ISSUE TITLE
OCPP 2.0(.1) implementation

### ISSUE THREAD

**Issue by Naheel-Azawy** [matth-x/MicroOcpp#82]
Hello @matth-x,

First, I would like to thank you for your great work here. Truly remarkable.
It seems that no one have asked for it yet, so I had to open a new issue.
Are there any plans to implement OCPP 2.0 and preferably 2.0.1?
I understand that this is big, but given the talent I see here it probably ain't that hard for you.

**Comment by matth-x** [comment]
Sorry that your issue remained unanswered. I'm closing this assuming it's no longer relevant.
