### ISSUE TITLE
changing cpp standard might affect the project execution?

### ISSUE THREAD

**Issue by VjSargunam** [matth-x/MicroOcpp#83]

**Comment by VjSargunam** [comment]
Hi matt,
           Currently my project supports c++11 standard. i need to use some advance feature for my main program to integrate with hardware. so i want to change the cpp standard from c++11 to c++20. Actually i try to change the standard in c_cpp_standards.json and saved the changes but once i restart the vscode the cpp standard automatically changes to c++11 irrespective of the changes i made previously in c_cpp_standards.json. How to sort out this issue.

Thanks
VJsargunam

**Comment by matth-x** [comment]
Sorry that your issue remained unanswered. I'm closing this assuming it's no longer relevant.
