### ISSUE TITLE
Build issue with Develop branch

### ISSUE THREAD

**Issue by whuizdis** [matth-x/MicroOcpp#87]
Hi @matth-x , As discussed with you earlier, I was looking for some of the changes you made to the develop branch and wanted to play around but hitting basic Compilation issues, while trying example file SECC . Hitting the following error, any clue to what I am missing?

n file included from /Users/phanigalla/Documents/Arduino/libraries/ArduinoOcpp/src/ArduinoOcpp/MessagesV16/StopTransaction.cpp:5:
/Users/phanigalla/Documents/Arduino/libraries/ArduinoOcpp/src/ArduinoOcpp/MessagesV16/StopTransaction.h:25:10: error: 'vector' in namespace 'std' does not name a template type
     std::vector<std::unique_ptr<MeterValue>> transactionData;
          ^~~~~~
/Users/phanigalla/Documents/Arduino/libraries/ArduinoOcpp/src/ArduinoOcpp/MessagesV16/StopTransaction.h:25:5: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
/Users/phanigalla/Documents/Arduino/libraries/ArduinoOcpp/src/ArduinoOcpp/MessagesV16/StopTransaction.h:11:1:
+#include <vector>
 
/Users/phanigalla/Documents/Arduino/libraries/ArduinoOcpp/src/ArduinoOcpp/MessagesV16/StopTransaction.h:25:5:
     std::vector<std::unique_ptr<MeterValue>> transactionData;
     ^~~
/Users/phanigalla/Documents/Arduino/libraries/ArduinoOcpp/src/ArduinoOcpp/MessagesV16/StopTransaction.h:33:68: error: 'std::vector' has not been declared
     StopTransaction(std::shared_ptr<Transaction> transaction, std::vector<std::unique_ptr<ArduinoOcpp::MeterValue>> transactionData);

**Comment by matth-x** [comment]
Hi, thank you for the report. This error wasn't easy to reproduce, but I found a condition where it occurs. Please check out this branch: [fix-87](https://github.com/matth-x/ArduinoOcpp/tree/fix-87)
