### ISSUE TITLE
Meter values 

### ISSUE THREAD

**Issue by nb4787** [matth-x/MicroOcpp#91]
can you explain about the meter value fucntion , how to print it on Serial monitor? 
it showing zero value in steve dashboard ..
![image](https://user-images.githubusercontent.com/60046470/191478722-673b9673-347b-4a0f-a012-f8d8ece399f0.png)

**Comment by nb4787** [comment]
zits showing empty in value , uint , phase , measurand section ?

**Comment by matth-x** [comment]
Sorry that your issue remained unanswered. I'm closing this assuming it's no longer relevant.
